import { Arrow, Check, Lock, Logo } from "./ui";
import { vpns } from "./site-data";

export function EditorialSection() { return <section className="editorial"><div className="container editorial-grid"><div className="editorial-visual"><span className="visual-label">EDITOR&apos;S NOTE</span><div className="visual-lock"><Lock /></div><span className="visual-caption">Your digital<br /><b>front door.</b></span></div><div className="editorial-copy"><div className="eyebrow">The short answer</div><h2>Why do you need a <span>VPN?</span></h2><p>A VPN is a simple privacy layer between you and the internet. It encrypts your connection, masks your IP address and gives you more control over where your data travels.</p><div className="editorial-points"><span><Check /> Encrypts your connection</span><span><Check /> Hides your IP address</span><span><Check /> Safer public Wi-Fi</span><span><Check /> Access your usual services</span></div><a className="button outline" href="#guides">Read our beginner&apos;s guide <Arrow /></a></div></div></section>; }

export function MethodologySection() { return <section className="section why" id="why"><div className="container why-grid"><div className="why-intro"><div className="eyebrow">Our methodology</div><h2>Good privacy advice starts with <span>good testing.</span></h2><p>VPN marketing can be noisy. We cut through it with hands-on testing and a clear scoring system you can trust.</p><a className="text-button" href="#faq">Learn more about our process <span>↗</span></a></div><div className="method-cards"><div className="method-card"><span className="method-number">01</span><h3>We test the basics</h3><p>Speed, security, server coverage and device support across real-world scenarios.</p></div><div className="method-card active"><span className="method-number">02</span><h3>We use it like you do</h3><p>Streaming, travel, remote work and everyday browsing—not just a lab checklist.</p></div><div className="method-card"><span className="method-number">03</span><h3>We keep it current</h3><p>Plans, features and performance are checked regularly as services evolve.</p></div></div></div></section>; }

export function ComparisonSection() { return <section className="section comparison" id="comparison"><div className="container"><div className="section-heading compact"><div><div className="eyebrow">Side-by-side</div><h2>Compare at a glance.</h2></div><p>Everything you need to find your fit.</p></div><div className="table-wrap"><table><thead><tr><th>VPN service</th><th>Our score</th><th>Best for</th><th>Servers</th><th>Devices</th><th>Starting price</th><th /></tr></thead><tbody>{vpns.map((vpn) => <tr key={vpn.name}><td><span className={`table-mark ${vpn.tone}`}>{vpn.mark}</span><b>{vpn.name}</b></td><td><strong className="table-score">{vpn.score}</strong> <span className="star">★</span></td><td>{vpn.badge}</td><td>{vpn.features[0].replace(" servers", "")}</td><td>{vpn.features[1].replace(" devices", "")}</td><td><b>{vpn.price}</b>/mo</td><td><a href="#" className="arrow-link"><Arrow size={16} /></a></td></tr>)}</tbody></table></div></div></section>; }

export function GuidesSection() { return <section className="section guides" id="guides"><div className="container"><div className="section-heading compact"><div><div className="eyebrow">Find your match</div><h2>A VPN for every <span>kind of online.</span></h2></div><p>Start with what matters most to you.</p></div><div className="guide-grid"><a href="#rankings" className="guide-card guide-blue"><span className="guide-icon">◉</span><h3>For streaming</h3><p>Watch more of your favorite shows, wherever you are.</p><span className="guide-arrow"><Arrow /></span></a><a href="#rankings" className="guide-card guide-dark"><span className="guide-icon">◒</span><h3>For privacy</h3><p>Keep your online activity private and your data yours.</p><span className="guide-arrow"><Arrow /></span></a><a href="#rankings" className="guide-card guide-sand"><span className="guide-icon">⌁</span><h3>For travel</h3><p>Stay connected safely on every unfamiliar network.</p><span className="guide-arrow"><Arrow /></span></a></div></div></section>; }

export function StoriesSection() { return <section className="section stories"><div className="container"><div className="section-heading compact"><div><div className="eyebrow">From the guide</div><h2>Useful, not <span>noisy.</span></h2></div><a className="text-button" href="#guides">View all guides <span>↗</span></a></div><div className="story-grid"><a className="story-card featured-story" href="#guides"><div className="story-art art-one"><span>01</span></div><div className="story-meta">VPN BASICS <span>6 min read</span></div><h3>VPNs explained: what they do and when you need one</h3><p>A clear, jargon-free guide to getting started with online privacy.</p></a><a className="story-card" href="#guides"><div className="story-art art-two"><span>02</span></div><div className="story-meta">STREAMING <span>8 min read</span></div><h3>How to choose a VPN for streaming in 2026</h3><p>Speed, location and the features that actually matter.</p></a><a className="story-card" href="#guides"><div className="story-art art-three"><span>03</span></div><div className="story-meta">TRAVEL <span>5 min read</span></div><h3>Public Wi-Fi: five simple ways to stay safer</h3><p>Practical habits for coffee shops, airports and hotels.</p></a></div></div></section>; }

export function VoicesSection() { return <section className="section voices"><div className="container"><div className="eyebrow">Reader voices</div><div className="voice-grid"><blockquote><div className="quote-stars">★★★★★</div><p>“Finally, a VPN comparison that explains the trade-offs without trying to sell me everything.”</p><footer>— Marcus T. <span>Verified reader</span></footer></blockquote><blockquote><div className="quote-stars">★★★★★</div><p>“The shortlist made choosing a VPN feel simple. I had mine set up in ten minutes.”</p><footer>— Aisha K. <span>Verified reader</span></footer></blockquote><blockquote><div className="quote-stars">★★★★★</div><p>“Clear, useful and up to date. The comparison table is exactly what I needed.”</p><footer>— Julia M. <span>Verified reader</span></footer></blockquote></div></div></section>; }

export function FaqSection() { return <section className="section faq" id="faq"><div className="container faq-grid"><div><div className="eyebrow">Still curious?</div><h2>Questions, <span>answered.</span></h2><p>We believe privacy tools should be easy to understand.</p></div><div className="faq-list"><details open><summary>What is a VPN? <span>+</span></summary><p>A VPN creates a secure connection between your device and the internet, helping keep your browsing private and protecting you on public Wi-Fi.</p></details><details><summary>How do you rank VPN services? <span>+</span></summary><p>We combine hands-on testing with research into security, performance, ease of use, support and overall value.</p></details><details><summary>Are VPNs legal to use? <span>+</span></summary><p>VPNs are legal in most countries. Local rules can vary, so always check the regulations where you live or travel.</p></details></div></div></section>; }

export function FooterSection() { return <><section className="final-cta"><div className="container final-inner"><div><div className="eyebrow light">Your privacy, your choice.</div><h2>Ready to find your VPN?</h2></div><a className="button light-button" href="#rankings">Explore the rankings <Arrow /></a></div></section><footer className="footer"><div className="container footer-grid"><div><Logo /><p>Independent VPN reviews<br />for a more private internet.</p></div><div><h4>Explore</h4><a href="#rankings">Best VPNs</a><a href="#guides">VPN guides</a><a href="#why">Our methodology</a></div><div><h4>Company</h4><a href="#faq">About VPNly</a><a href="#faq">Contact</a><a href="#faq">Privacy policy</a></div><div><h4>Stay in the know</h4><p className="newsletter-copy">The occasional privacy tip. No noise.</p><div className="newsletter"><input placeholder="Your email address" aria-label="Email address" /><button aria-label="Subscribe"><Arrow size={16} /></button></div></div></div><div className="container footer-bottom"><span>© 2026 VPNly. Built for a more open web.</span><span>We may earn a commission from links on this page.</span></div></footer></>; }
